apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynemic
spec:
  storageClassName: expense-sc 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynemic
  labels:
    purpose: ebs-dynemic
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynemic